#### 코드 참조 
[1] https://github.com/rickiepark/machine-learning-with-python-cookbook
[2] https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html 
[3] https://github.com/mikexcohen/LinAlgBook/blob/main/python

# 1장 벡터와 행렬

## 1.1 벡터 만들기

In [2]:
# 라이브러리를 임포트합니다.
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# 리스트
v_list = [1,2,3] 
v_list

[1, 2, 3]

In [4]:
v_tuple = (1, 2, 3)
v_dict = {'x':1, 'y':2, 'z':3}

In [5]:
# 배열(array), no orientation
v_array = np.array([1,2,3])
print(v_array)
v_array.shape

[1 2 3]


(3,)

In [6]:
# 행벡터를 만듭니다.
v_row = np.array([[1, 2, 3]])
print(v_row)
v_row.shape

[[1 2 3]]


(1, 3)

In [7]:
# 열벡터를 만듭니다.
v_column = np.array([[1],[2],[3]])
print(v_column)
v_column.shape

[[1]
 [2]
 [3]]


(3, 1)

In [8]:
v_row.T


array([[1],
       [2],
       [3]])

In [9]:
v_array.T


array([1, 2, 3])

In [10]:
new_row = np.asarray([1, 2, 3, 4])
new_row

array([1, 2, 3, 4])

In [11]:
# asarray()는 numpy arrary를 입력하면 새로운 배열을 만들지 않습니다.(뷰(view) 생성)
new_row = np.asarray(v_row)
new_row

array([[1, 2, 3]])

In [12]:
new_row is v_row

True

In [13]:
a = [1,2,3,4]
new = np.asarray(a)
a is new # a는 list, new는 numpy array이므로 False

False

In [14]:
# array()는 배열이 입력되면 새로운 배열을 만듭니다.(copy)
new_row = np.array(v_row)
new_row

array([[1, 2, 3]])

In [15]:
new_row is v_row

False

In [16]:
# copy() 메서드를 사용하면 의도가 분명해집니다.
new_row = v_row.copy()
new_row is v_row

False

## 1.2 벡터 연산

In [17]:
import numpy as np
# 벡터들
v_1 = np.array([5,4,7])
v_2 = np.array([3,4,5])
v_3 = np.array([4,1,0])
# 스칼라들(scalars)
c = [1, 2, -3]
# 선형결합
v_lin=c[0]*v_1 + c[1]*v_2 + c[2]*v_3
v_lin

array([-1,  9, 17])

In [18]:
# 마지막 원소를 선택합니다.
v_1[-1]

7

In [19]:
# 두 번째 원소를 포함하여 그 이전의 모든 원소를 선택합니다.
v_1[:2]

array([5, 4])

In [20]:
# 두 번째 이후의 모든 원소를 선택합니다.
v_1[2:]

array([7])

In [21]:
# 내적(dot product) = scalar
v_dp = np.dot(v_1,v_2)
v_dp

66

In [22]:
# 벡터곱(cross product) = vector
v_cp = np.cross(v_1,v_2)
v_cp

array([-8, -4,  8])

In [23]:
# 외적(outer product) = matrix
v_op = np.outer(v_1,v_2) 
v_op

array([[15, 20, 25],
       [12, 16, 20],
       [21, 28, 35]])

In [24]:
# 원소별 곱(Hadamard elementwise product)
v_m = v_1 * v_2
v_m

array([15, 16, 35])

In [25]:
# 노름(norm)
norm_v = np.linalg.norm(v_1)

# 단위백터
v_unit = v_1/ norm_v
v_unit

array([0.52704628, 0.42163702, 0.73786479])

In [26]:
np.linalg.norm?

In [56]:
# 벡터 리스트
v = [15, 16, 35, -5, 8, 2]
# 1 벡터
l1 = np.ones(len(v))

# 내적을 이용한 평균구하기(average via dot product)
ave = np.dot(v,l1) / len(v)
ave

11.833333333333334

## 1.3 행렬 만들기

In [65]:
# scipy.linalg operations can be applied equally to numpy.matrix or to 2D numpy.ndarray objects.
import numpy as np
from scipy import linalg

In [103]:
# 단위행렬(identity matrix)
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
# 1 행렬(ones matrix)
M1 = np.ones((5,5));
# 0 행렬(zeros matrix) (note the tuple input)
Z = np.zeros((5,5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
# 대각행렬(diagonal matrix)
D = np.diag([1,2,3,4,5]) 
D

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [30]:
# 대각원소들(diagonal elements)
R = np.random.randn(4,5)
R

array([[-1.25604096,  0.73021766,  1.28128974, -0.46002214, -1.81562496],
       [ 0.47746504,  0.51043223,  0.02541141, -0.34230392,  1.90044869],
       [ 0.48581697, -1.07722404, -0.74871761, -0.4520628 ,  0.9090105 ],
       [-0.55106455, -0.29118274,  0.39446599,  0.48955403,  0.56516738]])

In [31]:
d = np.diag(R)
d

array([-1.25604096,  0.51043223, -0.74871761,  0.48955403])

In [64]:
# 두개의 행렬(two matrices)
A = np.random.randn(5,4)
A

array([[ 0.81377701,  0.11410957, -1.4242916 , -0.89469774],
       [ 0.94779159,  0.76235321, -0.47201307,  0.73865025],
       [ 0.03807494, -1.07899498, -2.18507277,  1.17926954],
       [-0.27415989, -0.11685301,  2.56011987, -0.10758213],
       [-2.98829591, -1.20837302, -2.33470905,  0.0237657 ]])

In [65]:
B = np.random.randn(5,4)
B

array([[-1.33340449,  1.30498282, -0.51917814, -1.67705391],
       [-0.27903699, -0.40741746,  0.87571522,  1.20478351],
       [ 1.5724319 ,  0.74281098,  1.29829716,  0.22639806],
       [ 1.02925302,  1.44301409, -0.15704122, -0.53867501],
       [ 1.12108923,  1.40562535,  0.01539334,  0.16158569]])

In [66]:
# 열 연결
AB = np.concatenate((A,B),axis=1)
AB

array([[ 0.81377701,  0.11410957, -1.4242916 , -0.89469774, -1.33340449,
         1.30498282, -0.51917814, -1.67705391],
       [ 0.94779159,  0.76235321, -0.47201307,  0.73865025, -0.27903699,
        -0.40741746,  0.87571522,  1.20478351],
       [ 0.03807494, -1.07899498, -2.18507277,  1.17926954,  1.5724319 ,
         0.74281098,  1.29829716,  0.22639806],
       [-0.27415989, -0.11685301,  2.56011987, -0.10758213,  1.02925302,
         1.44301409, -0.15704122, -0.53867501],
       [-2.98829591, -1.20837302, -2.33470905,  0.0237657 ,  1.12108923,
         1.40562535,  0.01539334,  0.16158569]])

In [67]:
# 행 연결
AB = np.concatenate((A,B),axis=0)
AB

array([[ 0.81377701,  0.11410957, -1.4242916 , -0.89469774],
       [ 0.94779159,  0.76235321, -0.47201307,  0.73865025],
       [ 0.03807494, -1.07899498, -2.18507277,  1.17926954],
       [-0.27415989, -0.11685301,  2.56011987, -0.10758213],
       [-2.98829591, -1.20837302, -2.33470905,  0.0237657 ],
       [-1.33340449,  1.30498282, -0.51917814, -1.67705391],
       [-0.27903699, -0.40741746,  0.87571522,  1.20478351],
       [ 1.5724319 ,  0.74281098,  1.29829716,  0.22639806],
       [ 1.02925302,  1.44301409, -0.15704122, -0.53867501],
       [ 1.12108923,  1.40562535,  0.01539334,  0.16158569]])

In [88]:
# extract the lower triangle
L = np.tril(A)
L

array([[-0.92144285,  0.        ,  0.        ,  0.        ],
       [-0.37328371, -0.92040733,  0.        ,  0.        ],
       [ 2.0524748 ,  1.49350532, -0.29418328,  0.        ],
       [ 1.02339614, -0.10460799,  0.46218061,  0.168161  ]])

In [89]:
# extract the upper triangle
U = np.triu(A)
U

array([[-0.92144285,  0.73305961, -1.13147853,  1.00652149],
       [ 0.        , -0.92040733,  1.28309549, -2.23087532],
       [ 0.        ,  0.        , -0.29418328,  1.56804265],
       [ 0.        ,  0.        ,  0.        ,  0.168161  ]])

## 1.4 행렬연산

In [27]:
# 라이브러리를 임포트합니다.
import numpy as np
# 행렬을 만듭니다.
A = np.array([[1, 2, 3, 5],[2, 4, 6, 7],[3, 8, 9, 3], [10, 11, 12, 15]])
B = np.array([[1, 3, 1, 2],[1, 3, 1, 4],[1, 3, 2, 2],[4, 3, 5, 2]])

In [28]:
# 행렬의 크기를 확인합니다.
A.shape

(4, 4)

In [29]:
# 행렬의 원소 개수를 확인합니다(행 * 열).
A.size

16

In [30]:
# 차원 수를 확인합니다.
A.ndim

2

In [31]:
# 2x8 행렬로 크기를 바꿉니다.
A.reshape(2,8)

array([[ 1,  2,  3,  5,  2,  4,  6,  7],
       [ 3,  8,  9,  3, 10, 11, 12, 15]])

In [32]:
A.reshape(-1,8)

array([[ 1,  2,  3,  5,  2,  4,  6,  7],
       [ 3,  8,  9,  3, 10, 11, 12, 15]])

In [33]:
# 행렬을 펼칩니다.
A_flattened =A.flatten()
A_flattened

array([ 1,  2,  3,  5,  2,  4,  6,  7,  3,  8,  9,  3, 10, 11, 12, 15])

In [34]:
A_reshaped =A.reshape(-1)  # 또는 A.reshape(1,-1) 
A_reshaped

array([ 1,  2,  3,  5,  2,  4,  6,  7,  3,  8,  9,  3, 10, 11, 12, 15])

In [35]:
# (0, 0) 위치의 원소를 바꿉니다.
A[0][0] = -1
# reshaped 는 원본 배열의 변경 사항을 반영합니다.
A_reshaped

array([-1,  2,  3,  5,  2,  4,  6,  7,  3,  8,  9,  3, 10, 11, 12, 15])

In [36]:
# 복사된 배열에는 영향이 미치지 않습니다.
A_flattened

array([ 1,  2,  3,  5,  2,  4,  6,  7,  3,  8,  9,  3, 10, 11, 12, 15])

In [37]:
# matrix A의 세 번째 행, 두 번째 열의 원소를 선택합니다.
A[2,1]

8

In [38]:
# 행렬에서 첫 번째 두 개의 행과 모든 열을 선택합니다.
A[:2,:]

array([[-1,  2,  3,  5],
       [ 2,  4,  6,  7]])

In [39]:
# 행렬에서 세번째 행과 모든 열을 선택합니다.
A[2:,:]

array([[ 3,  8,  9,  3],
       [10, 11, 12, 15]])

In [40]:
# 모든 행과 두 번째 열을 선택합니다.
A[:,1:2]

array([[ 2],
       [ 4],
       [ 8],
       [11]])

In [41]:
np.trace(A)

27

In [42]:
# 대각합을 반환합니다.
A.trace()

27

In [43]:
# 대각 원소를 사용하여 합을 구합니다.
sum(A.diagonal())

27

In [44]:
# 주 대각선 하나 위의 대각 원소의 합을 반환합니다.
A.trace(offset=1)

11

In [45]:
# 주 대각선 하나 아래의 대각 원소의 합을 반환합니다.
A.trace(offset=-1)

22

In [46]:
# 가장 큰 원소를 반환합니다.
np.max(A)

15

In [83]:
A

array([[-1,  2,  3,  5],
       [ 2,  4,  6,  7],
       [ 3,  8,  9,  3],
       [10, 11, 12, 15]])

In [81]:
# 각 열에서 최댓값을 찾습니다.
np.max(A, axis=0)

array([10, 11, 12, 15])

In [82]:
# 각 행에서 최댓값을 찾습니다.
np.max(A, axis=1)

array([ 5,  7,  9, 15])

In [84]:
# 두 행렬을 더합니다.
np.add(A, B)

array([[ 0,  5,  4,  7],
       [ 3,  7,  7, 11],
       [ 4, 11, 11,  5],
       [14, 14, 17, 17]])

In [85]:
# 두 행렬을 더합니다.
A+B

array([[ 0,  5,  4,  7],
       [ 3,  7,  7, 11],
       [ 4, 11, 11,  5],
       [14, 14, 17, 17]])

In [86]:
# 두 행렬을 뺍니다.
np.subtract(A, B)

array([[-2, -1,  2,  3],
       [ 1,  1,  5,  3],
       [ 2,  5,  7,  1],
       [ 6,  8,  7, 13]])

In [87]:
A-B

array([[-2, -1,  2,  3],
       [ 1,  1,  5,  3],
       [ 2,  5,  7,  1],
       [ 6,  8,  7, 13]])

In [88]:
# 두 행렬을 곱합니다.
np.dot(A,B)

array([[ 24,  27,  32,  22],
       [ 40,  57,  53,  46],
       [ 32,  69,  44,  62],
       [ 93, 144, 120, 118]])

In [89]:
# 두 행렬을 곱합니다.
A@B

array([[ 24,  27,  32,  22],
       [ 40,  57,  53,  46],
       [ 32,  69,  44,  62],
       [ 93, 144, 120, 118]])

In [90]:
# 두 행렬을 곱합니다.
np.matmul(A,B)

array([[ 24,  27,  32,  22],
       [ 40,  57,  53,  46],
       [ 32,  69,  44,  62],
       [ 93, 144, 120, 118]])

In [91]:
# 두 행렬의 원소별 곱셈을 수행합니다.
A*B

array([[-1,  6,  3, 10],
       [ 2, 12,  6, 28],
       [ 3, 24, 18,  6],
       [40, 33, 60, 30]])

In [92]:
# 100을 더하는 함수를 만듭니다.
add_100 = lambda i: i + 100

# 벡터화된 함수를 만듭니다.
vectorized_add_100 = np.vectorize(add_100)
# 행렬의 모든 원소에 함수를 적용합니다.
vectorized_add_100(A)

array([[ 99, 102, 103, 105],
       [102, 104, 106, 107],
       [103, 108, 109, 103],
       [110, 111, 112, 115]])

In [93]:
# 모든 원소에 100을 더합니다.
A + 100

array([[ 99, 102, 103, 105],
       [102, 104, 106, 107],
       [103, 108, 109, 103],
       [110, 111, 112, 115]])

In [95]:
# (4, 4) 크기 행렬에 (4, ) 벡터를 더하면 
# (1, 4) 크기가 된다음 행을 따라 반복됩니다.
A + [100, 200, 300, 400]

array([[ 99, 202, 303, 405],
       [102, 204, 306, 407],
       [103, 208, 309, 403],
       [110, 211, 312, 415]])

In [96]:
# (4, 4) 크기 행렬에 (4, 1) 벡터를 더하면 열을 따라 반복됩니다.
A + [[100], [200], [300], [400]]

array([[ 99, 102, 103, 105],
       [202, 204, 206, 207],
       [303, 308, 309, 303],
       [410, 411, 412, 415]])

## 1.5 희소 행렬 만들기

In [105]:
# 라이브러리를 임포트합니다.
import numpy as np
from scipy import sparse

# 행렬을 만듭니다. 
matrix = np.array([[0, 0, 4, 2],
                   [0, 1, 0, 0],
                   [3, 0, 0, 0]])

# CSR (compressed sparse row) 행렬을 만듭니다.
matrix_sparse = sparse.csr_matrix(matrix)

In [106]:
# 희소 행렬을 출력합니다.
print(matrix_sparse)

  (0, 2)	4
  (0, 3)	2
  (1, 1)	1
  (2, 0)	3


In [107]:
# 큰 행렬을 만듭니다.
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# CSR 행렬을 만듭니다.
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# 큰 희소 행렬을 출력합니다.
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3
