# NumPy for Scientific Computation


**아래 링크를 통해 이 노트북을 주피터 노트북 뷰어(nbviewer.jupyter.org)로 보거나 구글 코랩(colab.research.google.com)에서 실행할 수 있습니다.**

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://nbviewer.jupyter.org/github/nhkim55/bigdata_fintech_python/blob/main/code/ch5_numpy.ipynb"><img src="https://jupyter.org/assets/main-logo.svg" width="28" />주피터 노트북 뷰어로 보기</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/nhkim55/bigdata_fintech_python/blob/main/code/ch5_numpy.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩(Colab)에서 실행하기</a>
  </td>
</table>

## 다차원 배열 객체-ndarray

In [ ]:
import numpy as np

In [ ]:
# 배열 생성
A = np.array([[1,2], [3,4]])
# 행렬 생성
B = np.matrix([[1,2],[3,4]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

matrix([[1, 2],
        [3, 4]])

In [ ]:
B

matrix([[1, 2],
        [3, 4]])

In [ ]:
matB = np.array([[3,1,9],[2,5,8],[4,7,6]]) # 리스트로 ndarray를 생성

matC = np.array(((3,1,9),(2,5,8),(4,7,6))) # 튜플로 ndarray를 생성

In [ ]:
matB.

In [ ]:
matC

array([[3, 1, 9],
       [2, 5, 8],
       [4, 7, 6]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
np.asarray(((1,2,3),(4,5,6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.arange([start,] stop[, step,][, dtype])
#### start로 지정한 값부터 stop 사이 값 중 step 간격을 갖는 수열을 생성한다



In [ ]:
# range로 생성
for i in range(10,20,2):
    print(i)

10
12
14
16
18


In [ ]:
a = [i for i in range(10,20,2)]
a

[10, 12, 14, 16, 18]

In [ ]:
# np.arange()로 생성
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### ndarray 데이터 타입 지정

In [ ]:
# dtype 객체로 지정
dt = np.dtype('float16')

# ndarray를 생성할 때 dtype으로 지정(dtype 객체 사용)
x = np.array([1.1, 2.1, 3.1], dtype=dt)

# ndarray를 생성할 때 dtype으로 지정(직접 문자열로 지정)
x = np.array([1.1, 2.1, 3.1], dtype='float16')

x.dtype

dtype('float16')

In [ ]:
a=[[1,2,3],[4,5,6]]

In [ ]:
a

[[1, 2, 3], [4, 5, 6]]

In [ ]:
a[1]

[4, 5, 6]

### ndarray 속성

In [ ]:
matB = np.array([[3,1,9],[2,5,8],[4,7,6]])

# ndarray의 크기를 반환
matB.shape

(3, 3)

In [ ]:
matB.shape?

### 행렬계산

In [ ]:
A = np.array([[-2,1],[1.5,-0.5]])
print(A)
# ‘linalg’는 선형대수를 위한 모듈
# A의 역행렬 계산
np.linalg.inv(A)

[[-2.   1. ]
 [ 1.5 -0.5]]


array([[1., 2.],
       [3., 4.]])

In [ ]:
A*A

array([[4.  , 1.  ],
       [2.25, 0.25]])

In [ ]:
# A의 행렬식 계산
np.linalg.det(A)

-0.5

In [ ]:
# A의 랭크를 계산
np.linalg.matrix_rank(A)

2

In [ ]:
# 벡터 a, b 정의
a, b = np.array([2,-4,1]), np.array([3,1,-2])

In [ ]:
# 벡터 a, b의 내적(scalar product)
np.inner(a,b)

0

In [ ]:
# 벡터 a, b의 외적(cross product)
np.cross(a,b)

array([ 7,  7, 14])

## ndarray 인덱싱

In [ ]:
x2d = np.arange(12).reshape(3,4)

# x2d의 내용 확인
x2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 두번째줄의 두번째 요소부터 전부 꺼낸다
a = x2d[1][1:]

# a의 내용 확인
a

array([5, 6, 7])

In [ ]:
# a의 일부 요소를 변환
a[0] = -1

# a는 뷰였으므로 x2d에도 변경의 영향이 미친다
x2d


array([[ 0,  1,  2,  3],
       [ 4, -1,  6,  7],
       [ 8,  9, 10, 11]])

### 기본 인덱싱

In [ ]:
# ndarray고유의 방법을 사용
b = x2d[1:, 2:]
b

array([[ 6,  7],
       [10, 11]])

In [ ]:
# 파이썬의 기본 리스트를 대상으로 위와 같이 슬라이싱하면 오류가 발생한다
k = [[1,2,3],[4,5,6]]

k[1,:]

TypeError: ignored

In [ ]:
k[1][:]

[4, 5, 6]

In [ ]:
b[:, :]=20

#b는 뷰이므로 위에서 변경한 결과가 x2d에도 반영된다
x2d

array([[ 0,  1,  2,  3],
       [ 4, -1, 20, 20],
       [ 8,  9, 20, 20]])

### 응용 인덱싱
#### 사본 생성

In [ ]:
### 부울(bool)값 인덱싱의 예
# 난수 값을 생성한다
dat = np.random.rand(2,3)
dat

array([[0.91251103, 0.08011912, 0.7743345 ],
       [0.37672757, 0.94898571, 0.85473575]])

In [ ]:
# 기준 0.5 값을 넘는 부울 값 배열을 만든다
bmask = dat > 0.5
bmask

array([[ True, False,  True],
       [False,  True,  True]])

In [ ]:
# ndarray dat에 대해 부울 값 배열로 인덱싱한다
highd = dat[bmask]
highd

array([0.91251103, 0.7743345 , 0.94898571, 0.85473575])

In [ ]:
# highd의 일부를 변경한다
highd[0] = 10
highd

array([10.        ,  0.7743345 ,  0.94898571,  0.85473575])

In [ ]:
# 위에서 highd를 변경했지만 dat에는 반영되지 않았다.  highd는 dat의 사본
dat

array([[0.91251103, 0.08011912, 0.7743345 ],
       [0.37672757, 0.94898571, 0.85473575]])

#### 정수 배열 인덱싱

In [ ]:
# 1차원 ndarray
nda = np.arange(10); nda

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 앞서 설명했던 기본 인덱싱의 방법(슬라이싱)으로 ndb라는 뷰를 만든다
ndb = nda[1:4]
ndb

array([1, 2, 3])

In [ ]:
# 정수 배열 인덱싱으로 ndc라는 사본을 만든다 (리스트의 형태로 인덱스를 넘긴다)
ndc = nda[[1,2,3]]
ndc

array([1, 2, 3])

In [ ]:
# ndb와 ndc는 그 내용이 같다
ndb == ndc
### ndb와 ndc는 같은 값을 갖고 있지만 ndc는 사본이므로 일부 요소의 값을 변경해도 원래 배열 nda에 영향을 미치지 못한다


array([ True,  True,  True])

In [ ]:
ndb is ndc

False

#### 여러 개의 배열을 사용한 인덱싱

In [ ]:
# 2차원 3x4 ndarray
nda = np.arange(12).reshape((3,4)); nda


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
### 여러 개의 배열을 사용한 인덱싱의 예
# 위치 (0,2), (2,0), (1,3)의 값을 꺼낸다
ndb = nda[[0,2,1], [2,0,3]]
ndb

array([2, 8, 7])

In [ ]:
### 특정 행과 열이 교차하는 자리에 위치한 요소를 꺼낼 때는 np.ix_ 함수를 사용한다
# (0,2)행과, (1,3)열이 교차하는 요소를 꺼낸다
nda[np.ix_([0,2], [1,3])]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
# Fortran과 같은 방식으로 열방향 우선 메모리 배치 지정
nda = np.arange(12).reshape(4,3,order='F')
print(nda)

# C와 같이 행방향 우선 메모리 배치 지정
ndb = np.zeros((3,3), order = 'C')



[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 유니버셜 함수

In [ ]:
# 2x6 ndarray를 만든다
nda = np.arange(12).reshape(2,6)

nda


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
# nda에 ufunc(square)를 적용하여 각 요소를 제곱한다
np.square(nda)


array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121]])

In [ ]:
np.sin?

 ## 브로드캐스팅

In [ ]:
# 1x3 ndarray
nda = np.array([1,2,3])

# 1x3 ndarray에 스칼라 1을 더한다
nda+1

array([2, 3, 4])

In [ ]:
nda = np.arange(24).reshape(4,3,2)

ndb = np.arange(6).reshape(3,2)

ndc = np.arange(3).reshape(3,1)

# 이 연산은 브로드캐스팅으로 수행이 가능하다
nda+ndb-ndc



array([[[ 0,  2],
        [ 3,  5],
        [ 6,  8]],

       [[ 6,  8],
        [ 9, 11],
        [12, 14]],

       [[12, 14],
        [15, 17],
        [18, 20]],

       [[18, 20],
        [21, 23],
        [24, 26]]])

In [ ]:
nda = np.arange(12).reshape(3,4)

# 크기 (4, )인 배열.   크기가 (4,1)이 아니란 것에 유의!
ndb = np.arange(4)

# 브로드캐스팅으로 계산 가능
nda + ndb


array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [ ]:
ndb = np.arange(4).reshape(4,1)

# 오류 발생
nda + ndb


ValueError: ignored